magick convert fh-am-bb-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bb-01.png
magick convert fh-am-bb-03.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bb-03.png
magick convert fh-am-bb-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bb-05.png
magick convert fh-am-bb-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bb-07.png
magick convert fh-am-bb-10.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bb-10.png
magick convert fh-am-bb-12.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bb-12.png
magick convert fh-am-bb-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bb-14.png
magick convert fh-am-bn-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bn-01.png
magick convert fh-am-bn-04.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bn-04.png
magick convert fh-am-bn-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bn-06.png
magick convert fh-am-bn-08.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bn-08.png
magick convert fh-am-bn-10.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bn-10.png
magick convert fh-am-bn-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bn-14.png
magick convert fh-am-bo-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bo-01.png
magick convert fh-am-bo-03.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bo-03.png
magick convert fh-am-bo-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bo-05.png
magick convert fh-am-bo-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bo-06.png
magick convert fh-am-bo-09.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bo-09.png
magick convert fh-am-bo-15.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bo-15.png
magick convert fh-am-bo-18.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-bo-18.png
magick convert fh-am-cr-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-cr-01.png
magick convert fh-am-cr-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-cr-05.png
magick convert fh-am-cr-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-cr-07.png
magick convert fh-am-cr-09.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-cr-09.png
magick convert fh-am-cr-13.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-cr-13.png
magick convert fh-am-cr-15.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-cr-15.png
magick convert fh-am-cr-16.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-cr-16.png
magick convert fh-am-df-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-01.png
magick convert fh-am-df-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-06.png
magick convert fh-am-df-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-07.png
magick convert fh-am-df-11.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-11.png
magick convert fh-am-df-13.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-13.png
magick convert fh-am-df-15.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-15.png
magick convert fh-am-df-16.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-16.png
magick convert fh-am-df-18.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-df-18.png
magick convert fh-am-dt-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dt-01.png
magick convert fh-am-dt-04.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dt-04.png
magick convert fh-am-dt-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dt-06.png
magick convert fh-am-dt-08.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dt-08.png
magick convert fh-am-dt-10.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dt-10.png
magick convert fh-am-dt-13.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dt-13.png
magick convert fh-am-dw-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dw-01.png
magick convert fh-am-dw-02.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dw-02.png
magick convert fh-am-dw-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dw-05.png
magick convert fh-am-dw-08.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dw-08.png
magick convert fh-am-dw-10.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dw-10.png
magick convert fh-am-dw-11.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dw-11.png
magick convert fh-am-dw-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-dw-14.png
magick convert fh-am-ff-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-01.png
magick convert fh-am-ff-03.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-03.png
magick convert fh-am-ff-04.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-04.png
magick convert fh-am-ff-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-05.png
magick convert fh-am-ff-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-07.png
magick convert fh-am-ff-09.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-09.png
magick convert fh-am-ff-11.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-11.png
magick convert fh-am-ff-12.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ff-12.png
magick convert fh-am-ge-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-01.png
magick convert fh-am-ge-02.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-02.png
magick convert fh-am-ge-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-05.png
magick convert fh-am-ge-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-07.png
magick convert fh-am-ge-09.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-09.png
magick convert fh-am-ge-11.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-11.png
magick convert fh-am-ge-13.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-13.png
magick convert fh-am-ge-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ge-14.png
magick convert fh-am-hv-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-hv-01.png
magick convert fh-am-hv-04.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-hv-04.png
magick convert fh-am-hv-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-hv-07.png
magick convert fh-am-hv-10.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-hv-10.png
magick convert fh-am-hv-12.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-hv-12.png
magick convert fh-am-hv-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-hv-14.png
magick convert fh-am-if-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-01.png
magick convert fh-am-if-02.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-02.png
magick convert fh-am-if-03.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-03.png
magick convert fh-am-if-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-05.png
magick convert fh-am-if-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-07.png
magick convert fh-am-if-09.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-09.png
magick convert fh-am-if-11.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-11.png
magick convert fh-am-if-17.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-if-17.png
magick convert fh-am-me-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-01.png
magick convert fh-am-me-04.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-04.png
magick convert fh-am-me-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-06.png
magick convert fh-am-me-08.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-08.png
magick convert fh-am-me-09.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-09.png
magick convert fh-am-me-12.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-12.png
magick convert fh-am-me-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-14.png
magick convert fh-am-me-15.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-me-15.png
magick convert fh-am-pc-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-01.png
magick convert fh-am-pc-02.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-02.png
magick convert fh-am-pc-03.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-03.png
magick convert fh-am-pc-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-06.png
magick convert fh-am-pc-07.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-07.png
magick convert fh-am-pc-10.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-10.png
magick convert fh-am-pc-16.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-16.png
magick convert fh-am-pc-18.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pc-18.png
magick convert fh-am-pm-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pm-01.png
magick convert fh-am-pm-16.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pm-16.png
magick convert fh-am-pm-26.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pm-26.png
magick convert fh-am-pm-back.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-pm-back.png
magick convert fh-am-py-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-py-01.png
magick convert fh-am-py-03.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-py-03.png
magick convert fh-am-py-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-py-05.png
magick convert fh-am-py-09.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-py-09.png
magick convert fh-am-py-11.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-py-11.png
magick convert fh-am-py-15.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-py-15.png
magick convert fh-am-sd-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sd-01.png
magick convert fh-am-sd-04.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sd-04.png
magick convert fh-am-sd-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sd-06.png
magick convert fh-am-sd-10.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sd-10.png
magick convert fh-am-sd-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sd-14.png
magick convert fh-am-sd-16.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sd-16.png
magick convert fh-am-sh-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sh-01.png
magick convert fh-am-sh-05.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sh-05.png
magick convert fh-am-sh-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sh-06.png
magick convert fh-am-sh-08.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sh-08.png
magick convert fh-am-sh-12.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sh-12.png
magick convert fh-am-sh-14.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-sh-14.png
magick convert fh-am-ta-01.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ta-01.png
magick convert fh-am-ta-03.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ta-03.png
magick convert fh-am-ta-06.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ta-06.png
magick convert fh-am-ta-12.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ta-12.png
magick convert fh-am-ta-16.png -matte ./mask.png -compose DstIn -composite ./rounded/fh-am-ta-16.png
magick convert p1_m1.png -matte ./mask.png -compose DstIn -composite ./rounded/p1_m1.png
magick convert p1_m2.png -matte ./mask.png -compose DstIn -composite ./rounded/p1_m2.png
magick convert p1_p0.png -matte ./mask.png -compose DstIn -composite ./rounded/p1_p0.png
magick convert p1_p1.png -matte ./mask.png -compose DstIn -composite ./rounded/p1_p1.png
magick convert p1_p2.png -matte ./mask.png -compose DstIn -composite ./rounded/p1_p2.png
magick convert p1_t0.png -matte ./mask.png -compose DstIn -composite ./rounded/p1_t0.png
magick convert p1_t2.png -matte ./mask.png -compose DstIn -composite ./rounded/p1_t2.png
magick convert p2_m1.png -matte ./mask.png -compose DstIn -composite ./rounded/p2_m1.png
magick convert p2_m2.png -matte ./mask.png -compose DstIn -composite ./rounded/p2_m2.png
magick convert p2_p0.png -matte ./mask.png -compose DstIn -composite ./rounded/p2_p0.png
magick convert p2_p1.png -matte ./mask.png -compose DstIn -composite ./rounded/p2_p1.png
magick convert p2_p2.png -matte ./mask.png -compose DstIn -composite ./rounded/p2_p2.png
magick convert p2_t0.png -matte ./mask.png -compose DstIn -composite ./rounded/p2_t0.png
magick convert p2_t2.png -matte ./mask.png -compose DstIn -composite ./rounded/p2_t2.png
magick convert p3_m1.png -matte ./mask.png -compose DstIn -composite ./rounded/p3_m1.png
magick convert p3_m2.png -matte ./mask.png -compose DstIn -composite ./rounded/p3_m2.png
magick convert p3_p0.png -matte ./mask.png -compose DstIn -composite ./rounded/p3_p0.png
magick convert p3_p1.png -matte ./mask.png -compose DstIn -composite ./rounded/p3_p1.png
magick convert p3_p2.png -matte ./mask.png -compose DstIn -composite ./rounded/p3_p2.png
magick convert p3_t0.png -matte ./mask.png -compose DstIn -composite ./rounded/p3_t0.png
magick convert p3_t2.png -matte ./mask.png -compose DstIn -composite ./rounded/p3_t2.png
magick convert p4m1.png -matte ./mask.png -compose DstIn -composite ./rounded/p4m1.png
magick convert p4p2.png -matte ./mask.png -compose DstIn -composite ./rounded/p4p2.png
magick convert p4t2.png -matte ./mask.png -compose DstIn -composite ./rounded/p4t2.png
magick convert p4_m2.png -matte ./mask.png -compose DstIn -composite ./rounded/p4_m2.png
magick convert p4_p0.png -matte ./mask.png -compose DstIn -composite ./rounded/p4_p0.png
magick convert p4_p1.png -matte ./mask.png -compose DstIn -composite ./rounded/p4_p1.png
magick convert p4_t0.png -matte ./mask.png -compose DstIn -composite ./rounded/p4_t0.png